### ISSUE TITLE
devexpress does not build with angular 12.1.3

### ISSUE THREAD

**Issue by MarjanGood** [DevExpress/DevExtreme#18502] opened 2021-07-28 12:42 UTC
### Steps to Reproduce:

1. 
2. 
3.

**Comment by MarjanGood** [comment] 2021-07-28 12:57
after updating, my project couldn't build and I've got this error

× Index html generation failed.
undefined:5:142920: property missing ':'

**Comment by LexDX** [comment] 2021-07-29 07:57
This is a duplicate of this issue: [https://github.com/DevExpress/DevExtreme/issues/17518](https://github.com/DevExpress/DevExtreme/issues/17518). Use recommendations from the initial issue to resolve the problem.

**Closed as completed by LexDX** 2021-07-29 07:57 UTC
Labels: duplicate

**Comment by MarjanGood** [comment] 2021-07-29 11:33
dear lexDX,
I am trying to fix my error and this is my error while I am building my project,

√ Copying assets complete.
× Index html generation failed.
undefined:5:142920: property missing ':'

, but this solution doesn't work for me,
"optimization": {
"scripts": true,
"styles": {
"minify": true,
"inlineCritical": false
},
"fonts": false
},

The error still persists in Angular v12 with ng build. (We're using devextreme 21.1.3)
Is there any other solution to solve this error?

> This is a duplicate of this issue: #17518. Use recommendations from the initial issue to resolve the problem.
