### ISSUE TITLE
TypeScript support enhancements

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#16455] opened 2021-02-20 11:26 UTC
# The Problem

DevExtreme TypeScript API includes areas that do not fully utilize TypeScript. It may affect overall developer experience. According to the feedback received from DevExtreme users, we can highlight the following main issues:

- Certain API members are declared as ‘any’.
- It is difficult to reuse internal types such as event/method arguments in user projects.

# The Proposed Solution

We plan to do the following:

- Replace the ‘any’ type with specific strong types wherever possible.
- Use strongly typed event arguments and extract these structures as named types/interfaces so you can use them in your projects.

For instance, we currently have the following declaration of the DataGrid's `onExporting` event:

```ts
export interface dxDataGridOptions extends GridBaseOptions<dxDataGrid> {
    onExporting?: ((e: { component?: dxDataGrid, element?: dxElement, fileName?: string, cancel?: boolean }) => any);
    // ...
}
```

In user projects, it usually appears as follows:

```ts
function handleExportingEvent(e: any) {
    // ...
}
```

We will extract event arguments as standalone interfaces:

```ts
export interface ExportingEvent {
    component?: dxDataGrid;
    element?: dxElement;
    fileName?: string;
    cancel?: boolean
}
export interface dxDataGridOptions extends GridBaseOptions<dxDataGrid> {
    onExporting?: (e: ExportingEvent) => void;
    // ...
}
```

You can use these extracted interfaces in your projects:

```ts
function handleExportingEvent(e: ExportingEvent) {
    // ...
}
```

# We Need Your Feedback

If you encounter issues that do not fall into the above mentioned categories, please add a comment in the section below, so we can address your specific use cases. Be sure to subscribe to this thread for updates on this topic as well.

**Comment by hakimio** [comment] 2021-02-24 19:50
Would be nice if DX store and datasource would have better typings as well.
Here is an example of some of custom typings we have used for reference:
[store](https://github.com/hakimio/dx-akita/blob/master/apps/dx-akita/src/app/shared/services/store/dx-store-manager/dx-store-manager.model.ts)
[load options](https://github.com/hakimio/dx-akita/blob/master/apps/dx-akita/src/app/shared/services/store/query-builder/query-builder.model.ts)

**Comment by Nisden** [comment] 2021-03-17 08:55
It would also be very nice if less of the properties on your events would be defined as nullable.
I have yet to see an event where the `component` was actually undefined or null.

**Comment by IlyaKhD** [comment] 2021-03-19 16:17
I agree, many properties are not actually optional. We'll check question marks and remove incorrect ones.

**Comment by IlyaKhD** [comment] 2021-04-28 08:39
We're happy to inform you that DevExtreme v21.1 contains types for event objects (arguments passed to event handlers).
Each component's module exports types for all its events. These types' names match the corresponding event names and have the -Event suffix.

Here is an import statement for [Button's Click](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxButton/Configuration/#onClick) event type:

```ts
import { ClickEvent } from 'devextreme/ui/button';

function handleClick(e: ClickEvent): void {
    // handling event
}
```

Also, we removed [optional](https://www.typescriptlang.org/docs/handbook/2/objects.html#optional-properties) modifiers from properties that are always defined. We marked properties that can be modified in a handler as non-[readonly](https://www.typescriptlang.org/docs/handbook/2/objects.html#readonly-properties).

**Comment by IlyaKhD** [comment] 2021-04-28 08:40
About JQuery types:
Previously, DevExtreme modules contained JQuery types regardless of whether your project used JQuery. For example, promises had the following type: `Promise<T> & JQueryPromise<T>`.

In v21.1, JQuery types are used only if you use JQuery. Otherwise, only built-in types are used. For example, promises have the following type: `Promise<T>`.

**Comment by IlyaKhD** [comment] 2021-04-28 08:41
To get DevExtreme v21.1 (it is currently in beta), run:
```console
npm install devextreme@21.1-next
```

Meanwhile, we keep working on our types. Here are our plans:


- Extract more reusable types
- Enhance data layer typings
- Use more specific types instead of `any`

Feel free to ask questions and suggest more enhancements.

**Comment by IlyaKhD** [comment] 2021-06-11 13:32
We're extending the DevExtreme TypeScript API and adding a lot of new types. To maintain consistency, we are reviewing existing type names and locations. At the same time, we're separating public types from internal ones to protect you from unnecessary breaking changes in the future.
More details in this discussion: #17885.

**Comment by Bykiev** [comment] 2021-07-04 15:04
@dxbykov, hello!

When using DevExtreme with angular `strictTemplates` compiler option enabled I can't use such type definitions with two-way binding defined. In production I'm getting this error:

```
Error: src/app/views/product/product.component.html:11:45 - error TS2322: Type 'string | number | Date' is not assignable to type 'Date'.
  Type 'string' is not assignable to type 'Date'.

11                     <dx-date-box [(value)]="endDate"
                                               ~~~~~~~~
12                                  type="date"
```

EndDate is defined in Component:
`endDate: Date;`

It should be defined as getter/setter in angular type definitions.

**Comment by hakimio** [comment] 2021-07-20 22:15
@Bykiev the DX type definition is correct. The problem is on your end. Your definition is not correct. Two way binding means that the value will be both read and written. The compiler is complaining because you can not assign string/number coming from the component side to your field typed as Date.

**Comment by Bykiev** [comment] 2021-07-21 07:39
> @Bykiev the DX type definition is correct. The problem is on your end. Your definition is not correct. Two way binding means that the value will be both read and written. The compiler is complaining because you can not assign string/number coming from the component side to your field typed as Date.

You're mistaken, the definition of `value` property as follows:

```
/**
* [descr:dxDateBoxOptions.value]
*/
value?: Date | number | string;
```

**Comment by hakimio** [comment] 2021-07-21 09:22
@Bykiev it corresponds official DX documentation:
https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDateBox/Configuration/#value

**Comment by Bykiev** [comment] 2021-07-21 10:03
@hakimio, sorry, I don't understand what you want to say. If I'll not use two-way bidning there are no errors, the issue with two-way binding in Angular.

According to the docs:
> If the UI component value is changed by an end-user, the new value is saved in the same format as the initial value.

**Comment by hakimio** [comment] 2021-07-21 10:26
Again, since you can't use TS generics in Angular component definition, the DX component property definition is correct. The issue is that the compiler doesn't know whether the `value` assigned by the component won't change to either number or string during runtime.

Here are some ways you can fix this on your end:
1. Use a function in your component class to cast the variable:
```html
 <dx-date-box [(value)]="asDate(endDate)"></dx-date-box>
```
```ts
export class MyComponent {

    asDate(date): Date { return date; }

}
```
2. Use a pipe to cast it:
```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'as',
  pure: true
})
export class AsPipe implements PipeTransform {

  transform<T>(value: any, class: new (...args: any[]) => T): T {
    return value as T;
  }

}
```
```html
<dx-date-box [(value)]="endDate | as: Date"></dx-date-box>
```
```ts
export class MyComponent {

    Date = Date;

}
```

**Comment by Bykiev** [comment] 2021-07-21 11:10
@hakimio, thank you for explanation!

**Upd:** second example with pipe is not correct as pipes cannot be used with template statement

**Comment by Mouna1001** [comment] 2021-07-22 14:39
Hello i'm new to devexpress i've done a pivot grid and i want to have just 2 digit after comma when clicking on sum or avg any idea how to do it .I've used this code https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/FieldPanel/Angular/Light/

**Comment by jakehockey10** [comment] 2021-08-05 19:26
Another example of strictTemplates not being supported is for DxProgressBar:

the value input is defined as a `number`, but the documentation says:
![image](https://user-images.githubusercontent.com/1821383/128409284-277c5ed8-6650-4af4-8005-d78213fae52d.png)
If I set the value to `false`, my project does not build.

![image](https://user-images.githubusercontent.com/1821383/128409387-470a38e5-080f-4101-bc0f-3a007e253150.png)

**Comment by IlyaKhD** [comment] 2021-08-25 07:37
@jakehockey10, thanks for pointing out this issue, we'll include a fix to one of the upcoming updates.

**Comment by VinzzB** [comment] 2021-09-23 21:58
After updating the devextreme package to v2.1.5 my TS code was throwing errors on React refs.
My web application is build upon React Hooks.  All useRef() hooks were throwing errors. Here is an example with a tagbox component (happens on all devex components):

```js
import { TagBox } from "devextreme-react";
import * as React from "react";
import { useRef } from "react";

const SomeFn = () => {

    const myRef = useRef<TagBox>(null);

    return <TagBox ref={myRef} />;
}
export default SomeFn;
```

The above code worked fine in previous versions, but results in the following error message in the new version:

```
Error	TS2322	(TS) Type '{ ref: MutableRefObject<TagBox>; }' is not assignable to type 'IntrinsicAttributes<P>'.
  Types of property 'ref' are incompatible.
    Type 'MutableRefObject<TagBox>' is not assignable to type 'Refs<P> | Ref<Element>'.
      Type 'MutableRefObject<TagBox>' is not assignable to type 'RefObject<Element>'.
        Types of property 'current' are incompatible.
          Type 'TagBox' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 123 more.
```

I can currently workaround this by casting the ref as an any object.
```js
return <TagBox ref={myRef as any} />;
```

Is it possible to add the typings for react hooks as well?  ( React.MutableRefObject< T >() )

**Comment by VinzzB** [comment] 2021-10-23 18:54
Just noticed in version 21.2.2 beta that the Type 'CustomItemCreatingEvent' on Tagbox.onCustomItemCreating() is bound to the SelectBox Type instead of the Tagbox.CustomItemCreatingEvent (which also exists)

Example:
```jsx

import { TagBox } from "devextreme-react";
import { CustomItemCreatingEvent } from "devextreme/ui/tag_box";
import * as React from "react";
import { useCallback } from "react";

const TestFn = () => {

    const createItem = useCallback((e: CustomItemCreatingEvent) => { }, [])

    return <TagBox
        onCustomItemCreating={createItem}
    />;
}
export default TestFn;
```

This gives the following compilation error:


> Error	TS2322	(TS) Type '(e: import("../ClientApp/node_modules/devextreme/ui/**tag_box**").CustomItemCreatingEvent) => void' is not assignable to type '(e: import("../ClientApp/node_modules/devextreme/ui/**select_box**").CustomItemCreatingEvent) => void'.
>   Types of parameters 'e' and 'e' are incompatible.
>     Type 'import("../ClientApp/node_modules/devextreme/ui/**select_box**").CustomItemCreatingEvent' is not assignable to type 'import("../ClientApp/node_modules/devextreme/ui/**tag_box**").CustomItemCreatingEvent'.
>       Type 'CustomItemCreatingEvent' is not assignable to type 'EventInfo<dxTagBox>'.
>         The types returned by 'component.instance().option()' are incompatible between these types.
>           Type 'Properties' is not assignable to type 'dxTagBoxOptions'.	..\ClientApp\src\TestComponent.tsx	14	Active
> 


Workaround: I've imported the Type from selectbox and used it on a TagBox.  
```jsx
import { CustomItemCreatingEvent } from "devextreme/ui/select_box";
```

**Comment by IlyaKhD** [comment] 2021-11-05 08:21
Hello @VinzzB!

I'm sorry for such a delay.
We were unable to reproduce the problem. Could you please share your tsconfig? It would be great if you share a sample project that demonstrates these compilation issues.

**Comment by VinzzB** [comment] 2021-11-16 12:52
Hello @IlyaKhD : I've created a new project where the same errors are thrown in my VS19 environment. 

Have a look at: https://github.com/VinzzB/DevExtremeTsTagBoxTest . (see App.tsx file)

Could this be a mismatch between my local npm and Visual studio? If i run 'npm run build' in a terminal window it will compile successfully. Only VS19 will show these errors.

**Comment by IlyaKhD** [comment] 2021-11-24 11:53
@VinzzB, thanks for the example - it helped a lot!

I managed to reproduce and investigate this issue.

The `onCustomItemCreating` problem is already fixed. The fix is included in the upcoming minor update: v21.2.4.

The `ref` problem is connected to the way Visual Studio resolves modules when searching for types.

I recommend the following:

1. Add a tsconfig.file to ClientApp. I think the best option is to use react-app defaults. When I was working with the example you shared, it was automatically generated during execution of `npm run build`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

Note that the file should be created in the ClientApp folder.

2. Ensure this tsconfig.json is properly included. Open the .csproj file (double-click the project in the solution explorer) and add these lines:

```xml
<Project ...>
...
  <ItemGroup>
    <Content Include="ClientApp\tsconfig.json" />
  </ItemGroup>
...
</Project>
```

**Comment by VinzzB** [comment] 2021-11-24 18:11
Hello @IlyaKhD : The tsconfig file is automatically generated (as you explained). I noticed that this file wasn't checked in when I pushed my test project to Git. My mistake. Luckily it was just the default tsconfig.

Your second step (adding tsconfig.json in VS projectfile) resolved the 'ref' issue in my projects. Thanks!

**Comment by ksercs** [comment] 2022-07-11 14:45
Thank you everybody, who gave us their feedback on this feature. We've implemented the major part of the typing enhancements. We'll be fixing specific issues as they appear. I'm closing this thread. In the case of bugs or questions, feel free to create a new ticket in our [Support Center](https://www.devexpress.com/Support/Center/).

**Closed as completed by ksercs** 2022-07-11 14:45 UTC
Labels: type/discussion, 21_1, 21_2
