### ISSUE TITLE
Form - Dynamic Updates without Full Re-rendering

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/DevExtreme#7295] opened 2019-03-15 07:35 UTC
# The Problem

The Form widget re-renders all its items when you change their count or reconfigure an individual item. 

# The Proposed Solution

We will add the `repaintChangesOnly` option that specifies whether the widget should repaint only those items whose data or configuration changed. 

```js
let formOptions = {
    repaintChangesOnly: true
};
```

**Note:** The Form re-renders all its items if your updates cause significant changes to the layout.

## Use Cases

The Form re-renders only an item whose options changed...

![show and hide an item](https://user-images.githubusercontent.com/11206389/54279671-b8461880-45a6-11e9-8ec3-d05cc3b736cd.gif)

... and newly added or removed items.

![add and delete an item](https://user-images.githubusercontent.com/11206389/54279659-b0867400-45a6-11e9-8d10-12e24ae96747.gif)

# Installation

Follow the installation guide from the [release page](https://github.com/DevExpress/DevExtreme/releases) and leave us feedback on this topic.

# We Need Your Feedback

Please share with us your additional partial form update scenarios by commenting on this thread.

## Take a Quick Poll

[Do you find this Form enhancement useful?](https://docs.google.com/forms/d/e/1FAIpQLSeXAmtkXg0cNSQsB3oQRs30ErOn0AtssSPWg0sqDn_hqI8tcA/viewform)

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by pedrofurtado** [comment] 2019-03-19 11:48
That is a great news! :tada:

**Comment by Ryan-Ketcham** [comment] 2019-03-19 13:42
In addition to showing/hiding fields based on values entered into other fields, we would also like to change validation rules on fields. As an example, if somebody entered their date of birth and said it is over 18, they would no longer have to add information for a Parent or Guardian. Right now we handle this validation with JavaScript, and to show/hide the fields we use CSS classes.

**Comment by pedrofurtado** [comment] 2019-03-19 16:17
@BingoRUS @dxbykov It will be good if the behavior of this component could replace libraries like these below:

Cocoon (Ruby on Rails) -> https://github.com/nathanvda/cocoon
Nova Repeatable Fields (Laravel) -> https://github.com/fourstacks/nova-repeatable-fields

**Comment by Shiko1st** [comment] 2019-03-19 23:12
Great news!

What are "significant changes"?
Will it be possible to add / hide /show tabs or groups dynamically?

**Comment by jsdmitry** [comment] 2019-03-22 09:26
@Ryan-Ketcham Thank you for your feedback. This functionality has been fixed in [#6433](https://github.com/DevExpress/DevExtreme/pull/6433).
@pedrofurtado Thank you for your idea. We'll check this library.
@Shiko1st By significant layout changes, we mean changes that require re-positioning of existing items between rows and columns. At the same time, if you update an item(s) within a single only, this group will be re-rendered.

**Comment by george-kar** [comment] 2019-03-24 19:42
That's was also a big issue for me and I can't wait for this update. Will be included on the 19.1 or we can expect it as update to the 18.x series ?

**Comment by dxbykov** [comment] 2019-04-02 11:47
> Will be included on the 19.1 or we can expect it as update to the 18.x series ?

It won't be a part of 18.x. According to the current development state, I'm afraid we can't release it in 19.1 with the desired level of quality. It's at the top of our to-do list, so if it's not ready by 19.1 we'll release it later this year. Please bear with us.

**Comment by hakimio** [comment] 2019-05-14 21:25
@dxbykov is this feature postponed until 19.2?

**Comment by dxbykov** [comment] 2019-05-15 11:25
Yes, we plan to release it in 19.2.

**Comment by jakehockey10** [comment] 2019-06-03 19:49
I apologize if there is an obvious answer, but where can I see the expected release date for 19.2?  I like what I see in the [Roadmap](https://js.devexpress.com/Roadmap/), but didn't know when this would be available and whether I should expect it soon or much later this year?

**Comment by hakimio** [comment] 2019-06-03 20:49
@jakehockey10 Like most .2 releases, most likely it will come around November.

**Comment by jakehockey10** [comment] 2019-06-04 13:53
Thanks for the response!

**Comment by jsdmitry** [comment] 2019-10-04 14:37
In the 19.2 version, will be add the capability of customizing DevExtreme Data Form item(s) within a group or tab (add/remove/display/hide) in code without re-rendering the entire form.
It means that if a form has an item(s), which will be changed at runtime, then it will be necessary to wrap these items in the group without a caption. So re-rendering will be performed only for this group.

**Comment by hakimio** [comment] 2019-10-04 17:53
@jsdmitry can you already provide some demo fiddle?

**Comment by jsdmitry** [comment] 2019-10-07 08:36
@hakimio I prepared the [fiddle](https://codepen.io/jsdmitry/pen/rNNNXzM?editors=0010).

**Comment by hakimio** [comment] 2019-10-07 08:45
@jsdmitry Awesome. Works really well and that's exactly what we need :)

**Comment by leandrogehlen** [comment] 2019-10-14 17:25
I have tested with `vue` the performance is better but the events are fired unnecessary


![dxform-vue](https://user-images.githubusercontent.com/1750751/66770614-78257c00-ee8e-11e9-96a3-80ac7922c7d8.gif)

**Comment by jsdmitry** [comment] 2019-10-15 10:50
@leandrogehlen Thank you for feedback. We will be researching the issue with unnecessary events.

**Comment by leandrogehlen** [comment] 2019-10-15 13:29
I believe the problem is  the binding:

```html
<dx-simple-item
   data-field="fantasia"
   editor-type="dxTextBox"
   v-if="tipoJuridica"
   :label="{text: $t('fantasia')}"
>
```

``` js
export default {
  components: {
    DxForm,
    DxLabel,
    DxSimpleItem,
    DxGroupItem,
    DxRequiredRule,
    DxCustomRule,
    DxEmailRule,
    DxButtonItem
  },

  mixins: [form],

  data() {
    return {
      registro: {
        tipo: 1
      }
    }
  }, 
  computed: {
    tipoJuridica() {
      return this.registro.tipo == 2;
    }
  }
```

**Comment by HASSANDL** [comment] 2019-10-16 08:34
```alignItemLabels``` not affect after hide and show element

![image](https://user-images.githubusercontent.com/22093903/66902179-0cb5e880-f00d-11e9-8801-c83dd2d3e507.png)

**Comment by jsdmitry** [comment] 2019-10-16 08:52
@HASSANDL This problem is known and we are working on it

**Comment by hakimio** [comment] 2019-11-20 14:26
@jsdmitry tried to recreate your example in Angular but unfortunately it did not work as expected.
I can't create online Fiddles with DevExtreme Angular, so here is a gist:
https://gist.github.com/hakimio/490a0725ab66fa44130ce39d49f3b9b2

Let me know if you can recreate the issue.

**Comment by jsdmitry** [comment] 2020-03-19 09:58
These features are now available in the [v19.2](https://github.com/DevExpress/DevExtreme/releases/tag/19.2.3) release. I'm closing this thread. In the case of bugs or questions, feel free to create new GitHub [issues](https://github.com/DevExpress/DevExtreme/issues) or tickets in our [Support Center](https://www.devexpress.com/Support/Center/).

**Closed as completed by jsdmitry** 2020-03-19 09:58 UTC
Labels: type/discussion, 19_2

**Comment by albertoVieiraNeto** [comment] 2020-12-24 12:04
i'm using 20.2 and this is still not included. neither in the documentation.

**Comment by hakimio** [comment] 2020-12-26 09:48
@albertoVieiraNeto it is included: [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/UpdateItemsDynamically/jQuery/Light/). It's just not obvious how to use it.

**Comment by w4ss1m9797** [comment] 2021-01-01 14:53
i'm using 20.2 and this is still not included. neither in the documentation.

**Comment by hakimio** [comment] 2021-01-01 20:07
@w4ss1m9797 are you "echo" bot?

**Comment by w4ss1m9797** [comment] 2021-01-01 22:08
> @w4ss1m9797 are you "echo" bot?

iam not thats the truth even i contacted support they told me use usememo and usecallback ... they know that it is not working with react

**Comment by hakimio** [comment] 2021-01-01 22:11
Maybe then you should open a new issue? This has nothing to do with React.

**Comment by w4ss1m9797** [comment] 2021-01-01 22:14
Listen , iam not here to argue , i just confirmed like others that this dynamic update not working maybe from my code but even contacted support no solution and i will open issue for sure

**Comment by hakimio** [comment] 2021-01-01 22:17
I am not arguing, just letting you know that posting here is not helpful to anyone.
Also, [React demo seems to be working in the demo page](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/UpdateItemsDynamically/React/Light/).

**Comment by w4ss1m9797** [comment] 2021-01-01 22:22
thanks bro , and abt this code i implemented it as iti is and run profiler it re render whole form :D

**Comment by hakimio** [comment] 2021-01-01 22:59
In the demo, only the form group is re-rendered (you can check with Chrome "Rendering" debugger if you don't believe me). Anyway, check how they have nested form item groups inside groups to get some idea how it supposed to work.
If you still can't make it work, create online demo showing what you are doing.

**Comment by mesut777** [comment] 2021-04-22 13:12
i am reading the documentation on:

https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxForm/

But there is not any "repaintChangesOnly" configuration for the form . Am i missing something ?

**Comment by hakimio** [comment] 2021-04-22 14:30
@mesut777 there is no "repaintChangesOnly" config for the form. You just have to nest form items in a specific way like shown in the [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/UpdateItemsDynamically/).

**Comment by quirogaco** [comment] 2021-10-19 14:53
when fields are hidden or shown in a form within a group in chrome too slow (using beginupdate, endupdate), in firefox the response is much faster 

chrome:
![chrome](https://user-images.githubusercontent.com/8965288/137935633-16526033-2640-47a5-a2eb-267258b2b055.png)

firefox:
![firefox](https://user-images.githubusercontent.com/8965288/137935808-94098c8c-17d5-433f-9fcb-c60b8576aa20.png)

**Comment by hakimio** [comment] 2021-10-19 15:02
@quirogaco you need to wrap the item groups you are toggling in another item group to avoid unwanted rerendering. When you do that, changes are instantaneous in both Chrome and Firefox like in the demo I linked above.

**Comment by theoneand2** [comment] 2022-02-11 08:50
@[hakimio](https://github.com/hakimio)

Brilliant Solution.
Wrapp the item which may change in a separate group and everything works fine. Thx
