### ISSUE TITLE
dxTreeList -> onSelectionChanged event don't return all of data 

### ISSUE THREAD

**Issue by samoilis** [DevExpress/DevExtreme#2783] opened 2018-01-31 15:55 UTC
I don't know if that is a bug issue or if is it by design behaviour

I use the Devextreme 17.2.5 and this issue concerns the dxTreeList widget with selection mode "multiple" and selection recursive true

if select a node with childs in onSelectionChanged event, the e.selectedRowsData returns only the data for the selected (parent) node and not all of the selected data (with child nodes)

this is an example of this behaviour:
https://jsfiddle.net/samoilis/LwkgdLhg/30/

**Comment by GoshaFighten** [comment] 2018-01-31 17:06
Duplicate of #2358.

**Closed as completed by GoshaFighten** 2018-01-31 17:06 UTC
Labels: duplicate
