### ISSUE TITLE
Datagrid is broken after resizing the window when there are fixed columns

### ISSUE THREAD

**Issue by Yura13** [DevExpress/DevExtreme#4795] opened 2018-07-25 09:30 UTC
### Steps to Reproduce:
Datagrid is broken after resizing the window when a cell has a validation rule and datagrid has fixed column.
Refer to example to see how to reproduce the issue:
https://codepen.io/Yurii13/pen/gjRedq

This issue was fixed in 18.1.4 (https://www.devexpress.com/Support/Center/Question/Details/T629168/datagrid-the-cannot-read-property-onresize-of-null-error-is-thrown), but actually it is not fixed.

![grid-resize-errors](https://user-images.githubusercontent.com/17030431/43192452-4947191c-9006-11e8-9b53-0c8b4d0b5f81.gif)

### Results You Received:
Errors are in console and datagrid is broken.

### Results You Expected:
Errors should not be shown in console and datagrid should not be broken.

### Environment Details:
devextreme: 18.1.4

**Comment by AntonSermyazhko** [comment] 2018-07-26 13:44
Hello,

I see the problem. I have reactivated the bug: https://www.devexpress.com/Support/Center/Question/Details/T629168/datagrid-the-cannot-read-property-onresize-of-null-error-is-thrown

**Comment by RezaRahmati** [comment] 2018-07-26 17:34
@Yura13 May I ask what software did you use to record your screen as gif?

**Comment by Yura13** [comment] 2018-07-27 07:02
@RezaRahmati Sure, it is ScreenToGif.

**Comment by Yura13** [comment] 2018-07-27 07:07
@AntonSermyazhko Could you please add the gif or link to the reproduced example to the reopened issue? Maybe it will be helpful for fixing.

**Comment by AntonSermyazhko** [comment] 2018-07-27 10:29
@Yura13 It turns out this problem is not related to the corresponding ticket. Please accept my apologies for misleading you.
We will process this issue in the context of the following thread.

**Comment by Yura13** [comment] 2018-07-27 12:59
@AntonSermyazhko It’s all right.
It will be great if you put here a link to the ticket of this issue. Thanks.

**Comment by AntonSermyazhko** [comment] 2018-07-31 14:11
The issue is resolved in #4852. I will update this thread when the fix is available.

**Comment by AntonSermyazhko** [comment] 2018-08-09 16:40
The fix is available now.
You can download or install/update the DevExtreme package via npm or bower:
 
[DevExpressDevExtreme-18.1.exe](http://downloads.devexpress.com/HotFixes/DevExtreme/v18.1)
[DevExpressDevExtreme-Complete-18.1.zip](http://downloads.devexpress.com/HotFixes/DevExtreme/v18.1/ZIP)

    npm install devextreme@18.1.6-pre-18221
    bower install devextreme#18.1.6-pre-18221

**Closed as completed** 2018-08-09 16:40 UTC
Labels: type/bug
