### ISSUE TITLE
TreeList selecting parent with selection recursive true, onselectionchanged e.currentSelectedRowKeys only shows parent no children

### ISSUE THREAD

**Issue by genachka** [DevExpress/DevExtreme#2646] opened 2018-01-25 01:09 UTC
Reopening as it's a feature request as discussed in https://github.com/DevExpress/DevExtreme/issues/2358

**Comment by AlekseyMartynov** [comment] 2018-01-26 09:53
Duplicate of #2358

@genachka 
Please use the original issue to continue the discussion.
We monitor tickets and receive updates regardless of whether they are open or closed.

**Closed as completed by AlekseyMartynov** 2018-01-26 09:53 UTC
Labels: duplicate

**Comment by genachka** [comment] 2018-01-28 18:42
@AlekseyMartynov which is why I asked for the original one to be re-opened. I get you get notifications, but that's not the same as tracking an issue that's open. Keeping an issue closed that is a feature request only makes sense if there's no plans to do anything with it, which is not the impression given.  That makes no sense.

**Comment by AlekseyMartynov** [comment] 2018-01-29 09:44
Please be sure that the team has taken into account your feedback from #2358.
DevExtreme feature planning and prioritization takes place in internal tools, not here on GitHub.
From https://github.com/DevExpress/DevExtreme/issues/2358#issuecomment-354462535 I understand that there's no outstanding issue requiring an action from our side.

If you need further assistance, please [contact our Support](https://github.com/DevExpress/DevExtreme/blob/17_2/CONTRIBUTING.md#issues-and-feature-requests).

**Comment by genachka** [comment] 2018-01-30 16:29
@AlekseyMartynov well that's the point, there is action required from DevExtreme as an enhancement since it clearly doesn't appear to work correctly. The GitHub approach for such is to leave the issue open and label with with enhancement until implemented. Unless of course there is no enhancement planned, which is not how I understood the response in #2358.

**Comment by GoshaFighten** [comment] 2018-01-30 18:01
@genachka 

I've replied to you in the #2358 issue with our vision of this issue. I believe everything is clear now.
