### ISSUE TITLE
dxBox can make dxSelectBox readonly

### ISSUE THREAD

**Issue by shawn-show** [DevExpress/DevExtreme#10186] opened 2019-10-14 15:25 UTC
If dxBox execute after dxSelectBox then dxSelectBox will be readonly

This is layout html.

    <div id="layout_body">
        <div data-options="dxItem: {ratio: 1}">
            <div id="user_page_menu_list"></div>
        </div>
        <div data-options="dxItem: {ratio: 5}">
            @RenderBody()
        </div>
    </div>
    <script>
     $('#layout_body').dxBox({
            direction: 'row',
            width: '100%'
        });
    </script>

This is the body html

    <div style="margin: 5%">
        <div id="user_info_form"></div>
    </div>
    <script>
      $('#user_info_form').dxForm({
        colCount: 2,
        formData:@Html.Raw(Json.Encode(ViewData["user_info"])),
        items: [{
            dataField:'name'
        }, {
            dataField:'telephone'
        }, {
            dataField: 'plant_FK',
            label: {
                    text:'Plant',
                },
                editorType: 'dxSelectBox',
                editorOptions: {
                    dataSource: @Html.Raw(Json.Encode(ViewData["plants"])),
                    displayExpr: 'name',
                    valueExpr: 'id',
                }
        }]
       })
    </script>

The only way to fixed it now is adding document ready on second html page.

So please fixed that

**Comment by AlisherAmonulloev** [comment] 2019-10-25 13:01
Your markup looks correct. The cause of the issue is unclear to me. Would you please create a simple runnable example demonstrating the issue so that I can debug it?

**Comment by AlisherAmonulloev** [comment] 2019-11-29 08:39
I am going to close this issue. Feel free to reactivate it if you need our assistance.

**Closed as completed by AlisherAmonulloev** 2019-11-29 08:39 UTC
